apiVersion: v1
kind: Service
metadata:
  name: nginx-logging-service
  namespace: test
spec:
  selector:
    task: nginx-logging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
